default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  username: myapp_user
  password: myapp_password
  host: localhost
  pool: 5

test:
  <<: *default
  database: myapp_test
  username: myapp_user        # Adjust if you have a different user for test
  password: myapp_password    # Adjust if you have a different password for test
  host: localhost

production:
  <<: *default
  database: myapp_production
  username: myapp_user        # Ensure this matches the user you created
  password: myapp_password    # Ensure this matches the password you set
  host: localhost

